// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTIProcessual.Data;

#nullable disable

namespace UTIProcessual.Migrations
{
    [DbContext(typeof(MVCDbContext))]
    [Migration("20221012160114_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UTIProcessual.Models.Cadastro.NovoProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Advogado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataDoCrime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascReu")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefensoriaPublica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoReu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FiliacaoReu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LocalDoCrime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NaturalidadeReu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeReu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumInqueritoPolicial")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPCNET")
                        .HasColumnType("int");

                    b.Property<int>("NumeroREDS")
                        .HasColumnType("int");

                    b.Property<string>("OABAdvogado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TelefoneReu")
                        .HasColumnType("int");

                    b.Property<string>("TipoPenal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CadastroProcessos");
                });
#pragma warning restore 612, 618
        }
    }
}
